### ISSUE TITLE
[Bug]: Following hyperlink from HotROD app does not find the trace on first try

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1180]
### What happened?

When clicking `[find trace]` hyperlink from the HotROD app for the first time, the search screen in the UI shows "No trace results. Try another query." Clicking on the same link again (which opens another tab with Jaeger UI) does find the trace.

### Steps to reproduce

1. in the jaeger repo, `cd examples/hotrod; docker-compose up`
2. open HotROD in http://localhost:8080/, hit one of the buttons
3. click on [find trace] link

### Expected behavior

the search results should show one trace. Instead, it shows error "No trace results. Try another query." The error goes away by reloading the page or repeating step 3 above.

### Jaeger backend version

1.41

**Comment by miikkuu** [comment]
@yurishkuro New to Contribution! Any help/suggestion with this one will be appreciated .
Thanks.

**Comment by miikkuu** [comment]
@yurishkuro How can this be solved?

**Comment by yurishkuro** [comment]
I don't know, investigating is part of the ticket.

**Comment by GLVSKiriti** [comment]
Hey @yurishkuro , I tested this issue in my local machine .What I observed is here
1.) Even though it is the first time  you click on "find trace" button after 3-4 seconds(approx.) it is showing trace
2.)Even if we are reloading page or again clicking on "find trace" before that 3-4 seconds it is not showing trace
3.)Sometimes we are not facing the issue even  before that 3-4 seconds
I think latency is due to  jaeger-ui for fetching trace-details from backend, Am I correct??

**Comment by yurishkuro** [comment]
In all in one the backend is all in memory, there is no delay. But there can be a delay before the trace data is exported from the hotrod app, depending on how the exporter is configured. In this testing app it should be exporting asap, not buffering.
