### ISSUE TITLE
Upgrade to ESM build of Vite

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#1985]
When running `yarn start` the following warning is printed:

> The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

According to the wiki, the CJS build will be removed in Vite v6.

* [ ] investigate & document what needs to change and what the implications are
* [ ] open PR with the required changes

**Comment by MeenuyD** [comment]
Hello @yurishkuro should we run the `npm install vite@latest --save-dev `

**Comment by yurishkuro** [comment]
why?

**Comment by ShivamMadlani** [comment]
hey @yurishkuro... in order to get rid of the warning we need to rename the `vite.config.ts` to `vite.config.mts`.

>> The closest package.json file has "type": "module", or use the .mjs/.mts extension, e.g. vite.config.mjs or vite.config.mts.

however, on doing this it throws an error on line 60 in `vite.config.ts` which states:
>TypeError: visualizer is not a function

i fixed this by reffering to https://www.npmjs.com/package/rollup-plugin-visualizer.

The warning is fixed now :). Should i open a PR?
