### ISSUE TITLE
Zipkin API support

### ISSUE THREAD

**Issue by rogueai** [jaegertracing/jaeger-ui#271]
Hi all, this is more of a discussion rather than an actual issue.
I've been working on a proof of concept to allow the Jaeger UI to query the Zipkin API instead.
Apart from some small changes, all I did so far was to transform the Zipkin API results from the V2 api when performing requests.

Everything is still very much work in progress, but I was wondering: would you consider, in the future, having something like this as part of your UI? I'm thinking about some sort of pluggable, or configurable, adapter to allow other tracing formats to be displayed.

Thank you for the work you're doing, the UI looks awesome :)

<img width="1438" alt="zipkin-ui" src="https://user-images.githubusercontent.com/945385/48051227-6dea0080-e19c-11e8-950f-74bbb8ddf091.png">

**Comment by yurishkuro** [comment]
We do not plan to support that. There are other ways you can do it:
  * you can replace Zipkin backend with Jaeger backend, since it can accept data in Zipkin format
  * you can build a proxy microservice that can sit between Zipkin backend and Jaeger UI and translate the API calls and data format on the fly.
