### ISSUE TITLE
Use time units in the Web UI which are easy to read by humans

### ISSUE THREAD

**Issue by cspurk** [jaegertracing/jaeger-ui#319]
## Requirement - what kind of business use case are you trying to solve?

Always use time units in the Web UI which are easy to read by humans.

We use Jaeger to trace some complex, long-running offline jobs in which a seconds granularity in the Web UI is too fine-grained for human consumption.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently, durations seem to be shown in either milliseconds (“ms”) or seconds (“s”). For traces of long-running requests/jobs a duration like “26904.23s” is not very readable.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Instead of showing a duration like “26904.23s”, a duration like “7.47 h” or even “7 h 28 m 24.23 s” would be better for human consumption.

**Comment by yurishkuro** [comment]
please indicate which views you are referring to

**Comment by cspurk** [comment]
> please indicate which views you are referring to

Not sure how they’re officially called but I guess any view would benefit. In particular I’m thinking about the search results view and the trace view.

**Comment by yogeshVU** [comment]
To add to this ticket, the time units to be displayed need to have a space after the number and before the time unit. 

for example:

`100 ms`  and not `100ms`
`200 s` and not `200s` 

I suppose this is as per the SI standards.
ref: https://english.stackexchange.com/questions/2794/punctuation-with-units

**Comment by yurishkuro** [comment]
Looks like the fix can go to https://github.com/jaegertracing/jaeger-ui/blob/master/packages/jaeger-ui/src/utils/date.tsx#L92

@yogeshVU my -1 was about spacing. I think `7h 28m 24s 235ms` or even  `7h28m24s235ms` is preferable over `7 h 28 m 24.23 s`.

**Comment by jamesfer** [comment]
Hello there, I found this issue because I was looking for an issue to work on as my first contribution and this one seemed pretty easy. 
I had some quick suggestions while I was implementing it though:
1. Limit the number of units displayed to the 3 closest to the largest unit. So only display hours, minutes and seconds, or seconds, milliseconds and microseconds, or days, hours and minutes. I think it might be too much to include microseconds if the duration is 7 hours long, for example.
2. Not include any units that are `0`. If a duration is exactly 5 minutes, then we should display `5m` instead of `5m 0s 0ms`.
3. Remove the `inputUnit` parameter from [`formatDate`](https://github.com/jaegertracing/jaeger-ui/blob/master/packages/jaeger-ui/src/utils/date.tsx#L92). I couldn't see the parameter used anywhere and it would simplify the `formatDate` implementation.
