### ISSUE TITLE
Unable to copy & paste span ID

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-ui#360]
## Requirement - what kind of business use case are you trying to solve?

I can't to highlight span IU to copy & paste it elsewhere.

## Problem - what in Jaeger blocks you from solving the requirement?

The popup shows saying  "click to add to filter", the span ID cannot be highlighted either by double-clicking or by dragging the mouse.

![image](https://user-images.githubusercontent.com/3523016/55026289-188e7e80-4fd9-11e9-8662-7c726a4eb0bc.png)

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add a magnifying glass for "click to add to filter" next to the span ID, leave span ID as plain text.

**Comment by everett980** [comment]
What are your thoughts on making the tooltip the clickable element instead?
Or instead of an add to filter icon, add a copy icon next to the ID which is a pattern present on KV tables and graph nodes?

Temporary work around: Right click the button (spanID) and select "copy"

**Comment by yurishkuro** [comment]
Copy button might work. What is the use case for adding span ID to the filter anyway? I am already looking at it.

**Comment by everett980** [comment]
The filter is shareable, so a user can add the ID then copy the url to send a link to a specific span within the trace. Or multiple spans if they select multiple IDs.

**Comment by tiffon** [comment]
@yurishkuro, @everett980 

I think it makes sense to have an icon for both filtering and copying. Currently, the filter functionality has a low level of discoverability.

OTOH, it's reasonable for the filter icon to actually be a share icon, since that's when adding it to the filter really makes sense.

Yuri, not sure if you're aware, but whatever is in the find input is added to the URL. And, if a URL with a `uiFind` value is viewed, then the parent spans that aren't ancestors of matching spans are collapsed and the spans that match have their details expanded. For instance, here is an entry with three matching spans:

![image](https://user-images.githubusercontent.com/3471184/51396551-47860100-1b0d-11e9-9891-4d9d74bdd1ad.png)

I think it makes to add a button on the Find input, near the up and down arrows, that triggers the collapsing of parents that aren't ancestors of matching nodes. Created #361 to capture this.

**Comment by tiffon** [comment]
Fixed in #367.
