### ISSUE TITLE
[trace timeline] Add a "collapse to matches" button next to the Find input

### ISSUE THREAD

**Issue by tiffon** [jaegertracing/jaeger-ui#361]
Add a button on the Find input, near the up and down chevrons, that triggers the collapsing of parent spans that aren't ancestors of matching nodes.

This would match the behaviour of loading the page when there is a `uiFind` value that has at least one match.

The button should be an icon, not the literal text "collapse to matches". Maybe the up and down buttons can be changed to arrows (instead of chevrons) and the icon for the new button can be the double-right chevron.

**Comment by everett980** [comment]
Having some issues with Icons atm. Icons that aren't used elsewhere in the project are blank. I think it is caused by using a slightly older version of antd that needs to load them all. If we update antd we'll get svg icons which would be nice.

Aside from that, the change is nearly ready. I still need to fix the Icons and add new tests, but there should be a diff for this sometime tomorrow 🤞

**Comment by everett980** [comment]
While working on this I noticed that expanding / collapsing many rows at once is a bit jarring. Based on the current implementation of detail rows and hidden children IDs I think it would be non-trivial to add some sort of transition to hiding/showing children and expanding/collapsing rows, but would make the experience a bit smoother.

**Comment by tiffon** [comment]
Fixed by #367.
