### ISSUE TITLE
How to group the trace?

### ISSUE THREAD

**Issue by hiepndd** [jaegertracing/jaeger-ui#464]
Hi,
I'm testing Jaeger with Go and I'm curious how to group the trace to visualize easily. 
For example: 
When I click to trace a `v1/example/:id` then Jaeger-UI show a drop-down list include (v1/example/1052, v1/example/1099 for example)
Thanks for your help!
Hiep

**Comment by yurishkuro** [comment]
This is a problem with your instrumentation that uses the actual URL as the span's operation name. If you read the semantic specs guidelines in OpenTracing, the URL should never be used as the operation name, precisely because of the problem you're seeing. In your case the appropriate operation name would be the literal string `/v1/example/:id`, aka "the route".
