### ISSUE TITLE
UI Lookback always assumes Browsers Local Date Time 

### ISSUE THREAD

**Issue by aveiros** [jaegertracing/jaeger-ui#535]
## Problem - what in Jaeger blocks you from solving the requirement?

UI always assumes Browser's local time while filtering the traces

For example, last two hours
start => NOW(GMT) - 2h
end =>   NOW(GMT)

If we set Jaeger Container/Server Date Time to the future (i.e. GMT + 2hours) and traces are being stored with this date time.

I can only see the traces if i use the Custom Date Time Range

**Comment by yurishkuro** [comment]
I don't see how that's a problem. What is your suggestion ?

**Comment by aveiros** [comment]
Every time someone wants to see traces, they have to pick custom date time and put a date-time in the future.

ISO 8601 Durations could be used to represent LAST 2 hours/and others and calculations are performed server-side instead of using browser date time.

**Comment by yurishkuro** [comment]
Doing so makes the query non-repeatable. Currently you can share the query URL with a colleague and they will (mostly) see similar results. But if the query contains the offsets instead of absolute time, the results are always going to be different. There are pros and cons for both.

As far as not seeing traces because of 2hr clock difference - why don't you run the server with the accurate time?

**Comment by aveiros** [comment]
I run the server in UTC usually. A distributed team would run into this problem.

Would someone during BST (GMT+1) only get 1-hour window if they picked last 2 hours?

Another suggestion could be the front end config "enforce" a timezone (if provided). per 1.

1) https://www.jaegertracing.io/docs/1.16/frontend-ui/

**Comment by yurishkuro** [comment]
I don't see how timezone is relevant. The UI submits timestamps as epoch numbers, which are time-zone agnostic.

**Comment by aveiros** [comment]
As you don't see a use case for this, I will close this ticket.
