### ISSUE TITLE
[bug] Navbar overlapping and css overflow in deep dependency section

### ISSUE THREAD

**Issue by meenal06** [jaegertracing/jaeger-ui#731]
## Current Behaviour

The deep dependency graph section overlaps and cutout the navigation bar when scrolled

## Expected Behaviour

Remove the css overflow and intersection of nav-bar

## Screenshot
<img width="1370" alt="Screenshot 2021-04-09 at 2 03 33 AM" src="https://user-images.githubusercontent.com/79007582/114092978-29686f00-98d8-11eb-8834-28235c1f9457.png">

**Comment by meenal06** [comment]
Hi @yurishkuro can you please assign me this issue?

**Comment by ampaire** [comment]
Hello, @yurishkuro has this issue been worked on?

**Comment by meenal06** [comment]
Hi, I didnt get time to complete it and I have my exams this week. Please
go ahead if you want to work on it.

**Comment by stardotcode** [comment]
I was able to repro this issue.

* the overlap happens when the window height is less than 680px
* the fixed page header element (`Page--topNav`) has `z-index: 3` ([Page.css:Line22](https://github.com/jaegertracing/jaeger-ui/blob/master/packages/jaeger-ui/src/components/App/Page.css#L22)), however the Deep Dependencies header element (`DdgHeader`) has `z-index: 10` ([index.css:Line25](https://github.com/jaegertracing/jaeger-ui/blob/master/packages/jaeger-ui/src/components/DeepDependencies/Header/index.css#L25)).

I'm not very familiar with the codebase yet, so don't know why the `z-index` is set to `10`.

A quick fix would be to bump the fixed page header element's `z-index` to `11`
